### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by vvlaw** [sundaymouse/srtmerge#1]
Hi,there.

when I tried to run the program, it has problem : 

vvlaw@archlinux  ~/splitsrt  python3 split.py                                                                                        
Traceback (most recent call last):
  File "split.py", line 23, in <module>
    InputFileName = sys.argv[1]
IndexError: list index out of range
 vvlaw@archlinux  ~/splitsrt 

**Comment by cnbeining** [comment]
You will need to supply the path for subtitle and a folder for output, like:

```
python split.py /path/to/original/subtitle.srt /path/to/output/subtitle
```

**Comment by vvlaw** [comment]
> You will need to supply the path for subtitle and a folder for output, like:
> 
> ```
> python split.py /path/to/original/subtitle.srt /path/to/output/subtitle
> ```

thanks for reply.

 vvlaw@archlinux  ~/splitsrt  python3 split.py /home/vvlaw/splitsrt/3.srt /home/vvlaw/splitsrt/                                                     127 ↵  5072  16:32:31
Reading from /home/vvlaw/splitsrt/3.srt .
File cannot be opened, check if file path is correct.

it looks like could not find the srt file.

**Comment by cnbeining** [comment]
You may want to ensure that no special character exists in any path.

**Comment by vvlaw** [comment]
> You may want to ensure that no special character exists in any path.

你好，我特意把文件名改成3.srt..

但是还是无法读取。。。

我试了用Aegisub打开srt文件，居然打开有错误。可能是从ass转过来的时候有错误 。。。

不过用了Isshawn的代码却可以顺利转换。就是没有批处理，有点可惜。
`https://github.com/lsshawn/srt-split-language/blob/main/split-language.py`

**Comment by vvlaw** [comment]
> 

yes. it looks like my srt file has problem.
